[build-system]
requires = ["setuptools", "wheel", "pybind11"]
build-backend = "setuptools.build_meta"

[project]
name = "flight_fms"
version = "0.0.1"
description = "Python package wrapper around the Flight Management System C++ extension"
authors = [{name = "Kabir"}]
dependencies = []